name: Mobile Binaries

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      buildFlags:
        required: false
        type: string
env:
  PROJECT_NAME: NightmareVision

jobs:
  Android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Most stable for Android builds
          java-version: '17'      # Use 11 or 17 depending on your NDK version

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV

      - name: Install Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg --quiet
          haxelib install compiletime --quiet
          haxelib run hxpkg install

      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Compile Android
        run: haxelib run lime build android -D ${{ inputs.buildFlags || '' }}

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NightmareVision-Android
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

  iOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Libs
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null --quiet
          haxelib install hxpkg
          haxelib install compiletime --quiet
          haxelib run hxpkg install --quiet

      - name: Compile iOS
        run: haxelib run lime build ios -nosign -D ${{ inputs.buildFlags || '' }}

      - name: Make IPA
        run: |
          brew install ldid
          cd export/release/ios/build/Release-iphoneos/NightmareVision.app
          ldid -S../../../NightmareVision/NightmareVision.entitlements NightmareVision
          cd ..
          mkdir Payload
          mv NightmareVision.app Payload
          zip -r NightmareVision.ipa Payload

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NightmareVision-iOS
          path: export/release/ios/build/Release-iphoneos/*.ipa

  Releaser:
    needs: [Android, iOS]
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Download Android Build
        uses: actions/download-artifact@main
        with:
           name: NightmareVision-Android
           path: /home/runner

      - name: Move Android File
        run: mv /home/runner/${{ env.PROJECT_NAME }}-release.apk /home/runner/${{ env.PROJECT_NAME }}-Android.apk

      - name: Download iOS Build
        uses: actions/download-artifact@main
        with:
           name: NightmareVision-iOS
           path: ${{ github.workspace }}

      - name: Move iOS File
        run: mv ${{ github.workspace }}/${{ env.PROJECT_NAME }}.ipa /home/runner/${{ env.PROJECT_NAME }}-iOS.ipa

      - name: Publish The Release
        uses: softprops/action-gh-release@v2
        with:
          name: "TEST 0.1"
          tag_name: "0.1"
          make_latest: true
          files: |
            /home/runner/*.apk
            /home/runner/*.ipa
